# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perssion',
            new_name='Permissions',
        ),
    ]
